deploy:
  provider: firebase
  skip_cleanup: true
  token:
    secure: "rDsRD77o5ZeJGtKmy04IOvJ6RUumpj0eJUriHBBlBEa+YyrUNnYxLH85fNZNyq+0HWWK/hM7KOrwjRetAUdYqtt4FyT9nQorJ7AbZrKHjsbaVwsSPY/Ixfsxte2EEVrAbyx0xQIW0UocbCdjpxhJyk7I6H2VVJWpu56gbXuL+4gCOIG/omwQR+zFj1c7EERVDN0LAM75IPfllQgbmWWLTiAziC5UD0uKO+AfNrhjjgjQwAT0BGTqJIs9uO1/4ByFYdP8P28D3Zsa5qcjv8xKzx18C6dYjdCMcDUP0tbe90joA4z1JN3IFzry/oH6TyEbTr0MYUm/v4l+dPTLpxSv5e+B8LWc4eXqaUXRQad9B7X2K1r4SYvKNeaAHWmIgb7FZP8CMhSRrY3G4M0BQjyglxVJew6/7OmZTu3yacabXGUtGycDBH/C9n13sOBnFcKYCSOavESHvribFZiqlm66Zs9ckbm0zDHR44pKERiJQpZ6mJ7gWVoOZz7BcA5Y16ShRY1rfviQSJmJn7YYb1iQD3m3ffX3u6BzuE3H2P7B7MvGfy8MALozSl7QbyW0pNAxx/maRroZfdEnZihZ9nkxy4iFwyjbuxYOAE9blzO6dder4t4F1L0cYWtjjmOVxDvgbyzjn3fhfS5IeZ7AC/H4TgNBuqEdmaui7wZvuW3KhK8="
  project: "ngx-renuo-upload-develop"
  on:
    branch: feature/change-firebase-configs
before_deploy:
- yarn build
language: node_js
dist: trusty
before_script:
- bin/setup
sudo: required
before_install:
- export DISPLAY=:99.0
- export TZ=Europe/Zurich
- sh -e /etc/init.d/xvfb start
- sleep 3
script:
- bin/check
- bin/check-server-start
cache:
  directories:
  - node_modules
env:
  global:
  - CXX=g++-4.8
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    - google-chrome
    packages:
    - zsh
    - g++-4.8
    - google-chrome-stable
after_failure:
  - cat /home/travis/build/renuo/ngx-renuo-upload/server_prod.log
