deploy:
  provider: firebase
  token:
    secure: "JYwC2fRncNNrjv2difqK6tdcpSMiTiKvRPMYAiwkPIjyE91CtEJ/7ZySwvThM4Wk9lG4cJ+Zs4qK17H2RL29848vuesBRmGWtJ5Tmy1woDu3xXP+5hRuZ8kDOH7/s3N/6SA4KYuiFn4nRMEztlbiUouFaWFXpfPro1IVctd7vtzqz7YrQE22JvzYx4qZrIlxpfTjNTKE9IceJl9TWlp95m/9OxYyC36K0U2qyEsxotTwzxf7HEBkOcIDHxah10rA99qL/nqZ1i5hkzno04ZudwUIsdUkECnAxRzQbt3Uqj+8iJS8iQi9h8DF7CkV1J6JUyRxo5JNLGcCCfxoZvbZs73ofZWLY/IAB/OmxpW2BVMljZ157CiKz73t6yT3jEiSuWxZlw6NLRcK/Th1MTtrWIEZK+RTFDETt27TszG1UcpiAuz/+MkCKIEs2anrfGhRoish5Hca+bNxUKt1tRaVesPp62aubeCM2MGNrkKmRYAz1o/+bezN/f1hhrGd+l3H/+XFUdGNfPMjYUDVOqvq7iTCHNu3OmH5QbmtvkNagwgROAb1aLEJBcfDPf8aBuAXhZlalDFQVpcpv2IhiPAixX+yCg+pBbe16kMQ9A8fagMtoW1ZFZgu3wwSdnI+HYREAtTdzr6rS/ntyyyfF9rn4jZu4Rv3a0wf8hpKNSIskBg="
  project: "ngx-renuo-upload-develop"
language: node_js
dist: trusty
before_script:
- bin/setup
sudo: required
before_install:
- export DISPLAY=:99.0
- export TZ=Europe/Zurich
- sh -e /etc/init.d/xvfb start
- sleep 3
script:
- bin/check
- bin/check-server-start
cache:
  directories:
  - node_modules
env:
  global:
  - CXX=g++-4.8
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    - google-chrome
    packages:
    - zsh
    - g++-4.8
    - google-chrome-stable
after_failure:
  - cat /home/travis/build/renuo/ngx-renuo-upload/server_prod.log
